server:
  port: 9092

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

security:
  oauth2:
    client:
      access-token-validity-seconds: 1800
      authorized-grant-types: password,refresh_token
      client-id: phoenix
      client-secret: $2a$10$p9Pk0fQNAQSesI4vuvKA0OZanDD2
      resource-ids: resources
      scope: read,write

spring:
  profiles:
    active: development

  datasource:
    schema: classpath:/sql/schema.sql
    data: classpath:/sql/data.sql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/phoenix?createDatabaseIfNotExist=true
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    
management:
  endpoints:
    web:
      exposure:
        include: '*'    
